### ISSUE TITLE
v0.1.0-beta Release

### ISSUE THREAD

**Issue by auguwu** [charted-dev/charted#1092]
* [x] ~~Finalize sessions crate with LDAP and GitHub integration for logging in~~ (#554) | LDAP support is *simple* and can break at any time, GitHub integration will come in a later release.
* [x] Finalize database crate with caching (#1050)
* [x] ~~Get Docker and Helm deployments working~~ (#1098) | Docker deployment is finished, Helm charts are being moved to [`charted-dev/helm-charts`](https://github.com/charted-dev/helm-charts)
* [x] ~~Finalize Noelware infra for charted (in `.noelware/deployment`)~~ This will be moved into its own repository
* [x] Finalize Logstash logging pipeline (as Logstash is a core part of Noelware's Observability pipeline) (#1097)
* [x] ~~Server Ratelimits~~ (#1083) | Implemented in a later release
* [x] Allow uppercase letters in `Name`s (#1216)
* [x] Validate `Name`s in `Path<NameOrSnowflake>` usages (#1217)

### API Keys
* [x] `GET /apikeys/{idOrName}`
* [ ] `DELETE /apikeys/{id}`
* [ ] `PATCH /apikeys/{id}`
* [ ] `PUT /apikeys`
* [x] `GET /apikeys`

### Organizations
* [x] `GET /organizations/{idOrName}/icon/{hash}`
* [x] `GET /organizations/{idOrName}/repositories`
* [x] `PUT /organizations/{idOrName}/repositories`
* [x] `POST /organizations/{idOrName}/icon`
* [x] `GET /organizations/{idOrName}`
* [x] `DELETE /organizations`
* [x] `PATCH /organizations`
* [x] `PUT /organizations`
* [x] `GET /organizations` 

### Repositories
* [x] `GET /repositories/{id}/releases/{version}/tarball`
* [x] `GET /repositories/{id}/releases/{version}/provenance`
* [x] `DELETE /repositories/{id}/releases/{version}`
* [x] `PUT /repositories/{id}/releases/{version}`
* [x] `GET /repositories/{id}/releases/{version}`
* [x] `PUT /repositories/{id}/releases`
* [x] `GET /repositories/{id}/releases`
* [x] `DELETE /repositories/{idOrName}`
* [x] `GET /repositories/{id}`
* [x] `PATCH /repositories`
* [x] `GET /repositories`

### Users
* [x] `GET /users/{idOrName}/repositories`
* [x] `GET /users/{idOrName}/avatar/{hash}`
* [x] `GET /users/{idOrName}/avatar`
* [x] `GET /users/@me/avatar/{hash}`
* [x] `PUT /users/@me/repositories`
* [x] `GET /users/{idOrName}`
* [x] `POST /users/@me/avatar`
* [x] `GET /users/@me/avatar`
* [x] `GET /users/@me`
* [x] `DELETE /users`
* [x] `PATCH /users` 
* [x] `PUT /users`
* [x] `GET /users` 

### Main
* [x] `GET /indexes/{idOrName}`
* [x] `GET /openapi.yaml`
* [x] `GET /openapi.json` 
* [x] `GET /cdn/{...path}`
* [x] `GET /features`
* [x] `GET /metrics`
* [x] `GET /info`
* [x] `GET /`

**Comment by auguwu** [comment]
Release is scheduled to be delayed from the initial January 1st release to Feburary 1st, 2024 due to delays with the team.

**Comment by auguwu** [comment]
We will release v0.1.0 as a stable release instead.
