### ISSUE TITLE
Finalize all deployments

### ISSUE THREAD

**Issue by auguwu** [charted-dev/charted#1098]
## Roadmap
- [x] Finalize Docker deployment (`cr.noelware.cloud/charted/server`) ~ Finished in commit [`ed0b4eed`](https://github.com/charted-dev/charted/commit/ed0b4eed3ddc0efba4bfc2851efd494e5bc92899)
- [x] ~~Finalize Helm deployment (`charts.noelware.org/~/charted/server`)~~ Development has moved to [`charted-dev/helm-charts`](https://github.com/charted-dev/helm-charts)
- [x] ~~Finalize Debian deployment (to Noelware's Artifacts Registry)~~ Not needed (yet)
- [x] ~~Finalize RPM deployment (to Noelware's Artifacts Registry)~~ Not needed (yet)
- [x] ~~Finalize Tar/Zip deployments (to Noelware's Artifacts Registry)~~ It'll be a flat binary to install
