### ISSUE TITLE
feat: tracing via OpenTelemetry/Elastic APM

### ISSUE THREAD

**Issue by auguwu** [charted-dev/charted#36]
This issue is the tracker for enabling tracing with charted's components (Docker Registry Proxy, Helm Charts Engine, Ktor), which will natively support:

- [Elastic APM](https://elastic.co/apm) (used by the official instance)
- [OpenTelemetry](https://opentelemetry.io)

## Tasks
- [ ] **Add `lib/tracing`, `lib/tracing/apm`, and `lib/tracing/opentelemetry` subprojects**
- [ ] **Finish and tested Elastic APM tracing**
- [ ] **Finish and tested OpenTelemetry tracing**
