### ISSUE TITLE
feat: add garbage collector

### ISSUE THREAD

**Issue by auguwu** [charted-dev/charted#38]
I feel like adding a "garbage collector" would be a neat feature to prune:

- inactive users that haven't been active,
- inactive repositories (that aren't in an archived/deprecated state),
- docker registry layers (if the Docker Registry feature is enabled)

This can be configured via the **GarbageCollectionConfig** struct, an example is shown below:

```yml
gc:
  inactive-repos: "last_published >= 30d"
  inactive-users: "last_logged_in >= 30d AND (username NOT EQUALS 'noel') OR (flags & (1 << 21)->isPresent)"
  docker-registry-layers: "last_pushed >= 30d"

  # This will schedule a cron job to run the garbage collector, admins can run the `POST /admin/gc` endpoint
  # to do it automatically.
  schedule:
    cron: "* * * * *"
```

> **Note**
> You can disable the garbage collector by using `gc: {}` or not adding the `gc` property in your configuration file.

The query language that is used in `inactive-repos` and such is called the **MQL** (mini-config query language) which is a mix of SQL and other kinds of generic QLs.

## Tasks
- [ ] Add `lib/gc`, `mql` subprojects
- [ ] Implement the "MQL" (min-config query language) via ANTLR4
- [ ] Implement garbage collector
